export {default as About } from './About'
export {default as Cart } from './Cart'

export {default as Error } from './Error'
export {default as HomeLayout } from './HomeLayout'
export {default as Landing } from './Landing'
// export {default as Login } from './Login'
// export {default as Orders } from './Orders'
export {default as Events } from './Events'
// export {default as Register } from './Register'
export {default as SingleEvent } from './SingleEvent'